import { Router, type IRouter } from "express";
import { db, tasksTable, shipmentsTable, paymentsTable, suppliersTable } from "@workspace/db";
import { and, asc, desc, eq, inArray } from "drizzle-orm";
import { resolveOrgId } from "../middlewares/requireAuth";
import { requireAiResult, runAi } from "../lib/ai-gateway";
import { z } from "zod";

const router: IRouter = Router();

const TODAY = "2026-05-18";

interface FocusItem {
  id: string;
  taskId: number | null;
  title: string;
  source: string;
  sourceAge: string;
  urgency: "high" | "medium" | "low";
  shipmentId: number;
  poNumber: string;
  supplierName: string;
  done: boolean;
  isAutoGenerated: boolean;
}

interface AiSuggestion {
  title: string;
  detail: string;
  action: string;
  poNumber: string;
  supplierName: string;
  shipmentId: number;
}

/** GET /api/focus — merged DB tasks + auto-generated urgency items */
router.get("/focus", async (req, res) => {
  const orgId = await resolveOrgId(req);

  // 1. Fetch real DB tasks
  const dbTasks = await db
    .select()
    .from(tasksTable)
    .where(eq(tasksTable.orgId, orgId))
    .orderBy(asc(tasksTable.id));

  // 2. Fetch active shipments with supplier info + overdue payments
  const shipments = await db
    .select({
      id: shipmentsTable.id,
      poNumber: shipmentsTable.poNumber,
      product: shipmentsTable.product,
      status: shipmentsTable.status,
      currentStageId: shipmentsTable.currentStageId,
      dueDate: shipmentsTable.dueDate,
      exFactoryDate: shipmentsTable.exFactoryDate,
      supplierName: suppliersTable.name,
    })
    .from(shipmentsTable)
    .leftJoin(suppliersTable, eq(shipmentsTable.supplierId, suppliersTable.id))
    .where(and(
      eq(shipmentsTable.orgId, orgId),
      inArray(shipmentsTable.status, ["on-track", "at-risk", "delayed"]),
    ));

  const overduePayments = await db
    .select()
    .from(paymentsTable)
    .where(and(eq(paymentsTable.orgId, orgId), eq(paymentsTable.paid, false)));

  const todayMs = new Date(TODAY).getTime();

  // 3. Build auto-generated urgency items
  const autoItems: FocusItem[] = [];
  const autoKeys = new Set<string>(); // deduplicate against DB tasks

  // Map existing DB task shipment+action combos so we skip duplicates
  for (const t of dbTasks) {
    autoKeys.add(`${t.shipmentId}:${t.action}`);
  }

  for (const ship of shipments) {
    const shipPmts = overduePayments.filter(p => p.shipmentId === ship.id);
    const supplier = ship.supplierName ?? "Unknown";

    // Overdue payments → high urgency balance wire reminders
    for (const pmt of shipPmts) {
      const overdueDays = Math.floor((todayMs - new Date(pmt.dueDate).getTime()) / 86_400_000);
      if (overdueDays <= 0) continue;
      const key = `${ship.id}:payment_overdue_${pmt.id}`;
      if (autoKeys.has(key)) continue;
      autoKeys.add(key);
      const ageLabel = overdueDays === 1 ? "Yesterday" : overdueDays < 7 ? `${overdueDays}d ago` : `${overdueDays}d ago`;
      autoItems.push({
        id: `auto_pmt_${pmt.id}`,
        taskId: null,
        title: `${pmt.label} overdue — ${supplier} (${ship.poNumber})`,
        source: "Tracker",
        sourceAge: ageLabel,
        urgency: overdueDays > 3 ? "high" : "medium",
        shipmentId: ship.id,
        poNumber: ship.poNumber,
        supplierName: supplier,
        done: false,
        isAutoGenerated: true,
      });
    }

    // Delayed / at-risk shipments without a matching high-urgency task
    if (ship.status === "delayed" || ship.status === "at-risk") {
      const key = `${ship.id}:status_alert`;
      if (!autoKeys.has(key)) {
        autoKeys.add(key);
        const daysUntilDue = ship.dueDate
          ? Math.floor((new Date(ship.dueDate).getTime() - todayMs) / 86_400_000)
          : null;
        const dueLabel = daysUntilDue === null
          ? ""
          : daysUntilDue < 0
            ? ` · ${Math.abs(daysUntilDue)}d overdue`
            : ` · due in ${daysUntilDue}d`;
        autoItems.push({
          id: `auto_status_${ship.id}`,
          taskId: null,
          title: `${ship.status === "delayed" ? "Delayed" : "At risk"} — ${supplier} ${ship.poNumber}${dueLabel}`,
          source: "Risk Radar",
          sourceAge: "Today",
          urgency: ship.status === "delayed" ? "high" : "medium",
          shipmentId: ship.id,
          poNumber: ship.poNumber,
          supplierName: supplier,
          done: false,
          isAutoGenerated: true,
        });
      }
    }
  }

  // 4. Merge: DB tasks first, then auto items not already covered
  const shipMap = new Map(shipments.map(s => [s.id, { poNumber: s.poNumber, supplierName: s.supplierName ?? "Unknown" }]));

  const urgencyOrder: Record<string, number> = { high: 0, medium: 1, low: 2 };

  const dbItems: FocusItem[] = dbTasks.map(t => {
    const ship = shipMap.get(t.shipmentId);
    return {
      id: `t${t.id}`,
      taskId: t.id,
      title: t.title,
      source: t.source,
      sourceAge: t.sourceAge,
      urgency: t.urgency as FocusItem["urgency"],
      shipmentId: t.shipmentId,
      poNumber: ship?.poNumber ?? "",
      supplierName: ship?.supplierName ?? "Unknown",
      done: t.done,
      isAutoGenerated: false,
    };
  });

  const merged = [...dbItems, ...autoItems].sort((a, b) => {
    if (a.done !== b.done) return a.done ? 1 : -1;
    return (urgencyOrder[a.urgency] ?? 2) - (urgencyOrder[b.urgency] ?? 2);
  });

  const pendingCount = merged.filter(i => !i.done).length;

  res.json({ items: merged, pendingCount });
});

/** PATCH /api/focus/:id — toggle done for a DB task (auto items are read-only) */
router.patch("/focus/:id", async (req, res) => {
  const rawId = req.params.id;
  if (!rawId.startsWith("t")) {
    res.status(400).json({ error: "Only real DB tasks can be toggled" });
    return;
  }
  const taskId = Number(rawId.slice(1));
  const orgId = await resolveOrgId(req);
  const { done } = z.object({ done: z.boolean() }).parse(req.body);
  const [updated] = await db
    .update(tasksTable)
    .set({ done })
    .where(and(eq(tasksTable.id, taskId), eq(tasksTable.orgId, orgId)))
    .returning();
  if (!updated) {
    res.status(404).json({ error: "Task not found" });
    return;
  }
  res.json({ id: rawId, done: updated.done });
});

/** POST /api/focus/suggestions — AI suggestions from live shipment data */
router.post("/focus/suggestions", async (req, res) => {
  const orgId = await resolveOrgId(req);

  const shipments = await db
    .select({
      id: shipmentsTable.id,
      poNumber: shipmentsTable.poNumber,
      product: shipmentsTable.product,
      status: shipmentsTable.status,
      currentStageId: shipmentsTable.currentStageId,
      dueDate: shipmentsTable.dueDate,
      exFactoryDate: shipmentsTable.exFactoryDate,
      supplierName: suppliersTable.name,
    })
    .from(shipmentsTable)
    .leftJoin(suppliersTable, eq(shipmentsTable.supplierId, suppliersTable.id))
    .where(and(
      eq(shipmentsTable.orgId, orgId),
      inArray(shipmentsTable.status, ["on-track", "at-risk", "delayed"]),
    ));

  const overduePayments = await db
    .select()
    .from(paymentsTable)
    .where(and(eq(paymentsTable.orgId, orgId), eq(paymentsTable.paid, false)));

  const todayMs = new Date(TODAY).getTime();

  const contextLines = shipments.map(s => {
    const pmts = overduePayments.filter(p => p.shipmentId === s.id);
    const overduePmts = pmts.filter(p => new Date(p.dueDate).getTime() < todayMs);
    const daysUntilDue = s.dueDate
      ? Math.floor((new Date(s.dueDate).getTime() - todayMs) / 86_400_000)
      : null;
    return [
      `• ${s.poNumber} (${s.product}) — supplier: ${s.supplierName ?? "unknown"}, status: ${s.status}, stage: ${s.currentStageId.replace(/_/g, " ")}, ex-factory: ${s.exFactoryDate}, due: ${s.dueDate ?? "?"}${daysUntilDue !== null ? ` (${daysUntilDue < 0 ? Math.abs(daysUntilDue) + "d overdue" : "in " + daysUntilDue + "d"})` : ""}`,
      overduePmts.length > 0
        ? `  ⚠ Overdue payments: ${overduePmts.map(p => `${p.label} $${p.amountUsd} (due ${p.dueDate})`).join(", ")}`
        : null,
    ].filter(Boolean).join("\n");
  }).join("\n");

  const systemPrompt = `You are FlowForgeIQ, an AI assistant for a supply-chain buyer. Today is ${TODAY}.

ACTIVE SHIPMENTS:
${contextLines || "No active shipments."}

Generate exactly 3 concise, high-value action suggestions the buyer should take TODAY. Each suggestion must be specific to a real shipment above — use exact PO numbers and supplier names.

Respond with a JSON array (no markdown, no wrapper object) containing exactly 3 objects:
[
  {
    "title": "Short action label (max 12 words)",
    "detail": "One sentence of context with dollar amounts or dates where relevant",
    "action": "Action verb phrase (e.g. 'Draft wire reminder', 'Follow up QC pass', 'Escalate port delay')",
    "poNumber": "PO-XXXX",
    "supplierName": "Supplier Name",
    "shipmentId": 123
  }
]

Focus on: overdue payments → balance wire reminders, at-risk/delayed shipments → follow-up or escalation, ready-to-advance stages → QC pass or ex-factory confirmation.`;

  let suggestions: AiSuggestion[] = [];
  try {
    const requestId = req.headers["x-request-id"];
    const correlationId = typeof requestId === "string" && requestId.trim() ? requestId : undefined;
    const parsed = requireAiResult(await runAi<unknown>({
      metadata: {
        orgId,
        workflow: "focus",
        event: "suggestions",
        conversationId: `focus:suggestions:org:${orgId}`,
        ...(correlationId ? { correlationId } : {}),
      },
      model: "gpt-5-mini",
      messages: [{ role: "system", content: systemPrompt }],
      maxCompletionTokens: 1024,
      responseFormat: { type: "json_object" },
      output: "json",
    }));
    // Model may wrap in an object despite instructions — unwrap
    const arr = Array.isArray(parsed) ? parsed : (parsed as Record<string, unknown>).suggestions ?? (parsed as Record<string, unknown>).items ?? Object.values(parsed as object)[0];
    suggestions = (Array.isArray(arr) ? arr : []).slice(0, 3) as AiSuggestion[];
  } catch {
    suggestions = [];
  }

  res.json({ suggestions });
});

export default router;
