// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nav-redesign/CopilotAIDrawer.tsx": () => import("../components/mockups/nav-redesign/CopilotAIDrawer.tsx"),
  "./components/mockups/nav-redesign/CopilotActionCenter.tsx": () => import("../components/mockups/nav-redesign/CopilotActionCenter.tsx"),
  "./components/mockups/nav-redesign/ReportsRisk.tsx": () => import("../components/mockups/nav-redesign/ReportsRisk.tsx"),
  "./components/mockups/nav-redesign/UnifiedInbox.tsx": () => import("../components/mockups/nav-redesign/UnifiedInbox.tsx"),
  "./components/mockups/nav-redesign/UnifiedShipments.tsx": () => import("../components/mockups/nav-redesign/UnifiedShipments.tsx"),
  "./components/mockups/pdf-field-viewer/HoverPopover.tsx": () => import("../components/mockups/pdf-field-viewer/HoverPopover.tsx"),
  "./components/mockups/pdf-field-viewer/InlineSnippet.tsx": () => import("../components/mockups/pdf-field-viewer/InlineSnippet.tsx"),
  "./components/mockups/pdf-field-viewer/SplitPane.tsx": () => import("../components/mockups/pdf-field-viewer/SplitPane.tsx"),
  "./components/mockups/flowforge/Atelier.tsx": () => import("../components/mockups/flowforge/Atelier.tsx"),
  "./components/mockups/flowforge/ConversationHub.tsx": () => import("../components/mockups/flowforge/ConversationHub.tsx"),
  "./components/mockups/flowforge/OrdersLayoutA.tsx": () => import("../components/mockups/flowforge/OrdersLayoutA.tsx"),
  "./components/mockups/flowforge/OrdersLayoutB.tsx": () => import("../components/mockups/flowforge/OrdersLayoutB.tsx"),
  "./components/mockups/flowforge/OrdersLayoutC.tsx": () => import("../components/mockups/flowforge/OrdersLayoutC.tsx"),
  "./components/mockups/flowforge/OrdersLayoutCanvas.tsx": () => import("../components/mockups/flowforge/OrdersLayoutCanvas.tsx"),
  "./components/mockups/flowforge/POVariantA.tsx": () => import("../components/mockups/flowforge/POVariantA.tsx"),
  "./components/mockups/flowforge/POVariantB.tsx": () => import("../components/mockups/flowforge/POVariantB.tsx"),
  "./components/mockups/flowforge/POVariantC.tsx": () => import("../components/mockups/flowforge/POVariantC.tsx"),
  "./components/mockups/flowforge/ShipmentAtlas.tsx": () => import("../components/mockups/flowforge/ShipmentAtlas.tsx"),
  "./components/mockups/flowforge/TodaysFocusCanvas.tsx": () => import("../components/mockups/flowforge/TodaysFocusCanvas.tsx"),
  "./components/mockups/flowforge/TodaysFocusSlideout.tsx": () => import("../components/mockups/flowforge/TodaysFocusSlideout.tsx")
};
