kind = "mobile"
previewPath = "/flowforge-mobile/"
title = "FlowForge Mobile"
version = "1.0.0"
id = "artifacts/flowforge-mobile"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
name = "expo"
paths = [ "/flowforge-mobile/" ]
localPort = 3000

[services.development]
run = "pnpm --filter @workspace/flowforge-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/flowforge-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/flowforge-mobile", "run", "serve" ]

[services.env]
PORT = "3000"
BASE_PATH = "/flowforge-mobile/"
