import React, { useState, useEffect, useRef } from "react";
import { Zap, X, Check, Sparkles, ArrowRight, Loader2, ChevronRight, AlertCircle } from "lucide-react";
import { useListFocusItems, useUpdateFocusItem } from "@workspace/api-client-react";
import type { FocusItem, AiSuggestion } from "@workspace/api-client-react";
import { useLocation } from "wouter";

interface TodaysFocusDrawerProps {
  open: boolean;
  onClose: () => void;
}

const URGENCY_DOT: Record<string, string> = {
  high: "bg-red-500",
  medium: "bg-amber-400",
  low: "bg-emerald-400",
};

const SOURCE_ICON: Record<string, string> = {
  WhatsApp: "💬",
  Gmail: "✉️",
  Tracker: "🗂️",
  Sheets: "📊",
  "Risk Radar": "⚠️",
  default: "📌",
};

function sourceIcon(source: string) {
  return SOURCE_ICON[source] ?? SOURCE_ICON.default;
}

export function TodaysFocusDrawer({ open, onClose }: TodaysFocusDrawerProps) {
  const [, setLocation] = useLocation();
  const { data, refetch } = useListFocusItems();
  const updateMutation = useUpdateFocusItem();
  const [suggestionsLoaded, setSuggestionsLoaded] = useState(false);
  const [suggestions, setSuggestions] = useState<AiSuggestion[]>([]);
  const [suggestionsLoading, setSuggestionsLoading] = useState(false);
  const [suggestionsError, setSuggestionsError] = useState(false);
  const fetchedRef = useRef(false);
  const basePath = import.meta.env.BASE_URL.replace(/\/$/, "");

  const items: FocusItem[] = data?.items ?? [];
  const pendingCount = data?.pendingCount ?? 0;
  const doneCount = items.filter(i => i.done).length;
  const totalCount = items.length;

  // Load AI suggestions once when drawer first opens
  useEffect(() => {
    if (!open || fetchedRef.current) return;
    fetchedRef.current = true;
    setSuggestionsLoading(true);
    setSuggestionsError(false);
    void fetch(`${basePath}/api/focus/suggestions`, { method: "POST" })
      .then(r => r.json())
      .then((d: { suggestions: AiSuggestion[] }) => {
        setSuggestions(d.suggestions ?? []);
        setSuggestionsLoaded(true);
      })
      .catch(() => { setSuggestionsError(true); })
      .finally(() => { setSuggestionsLoading(false); });
  }, [open, basePath]);

  const toggleItem = async (item: FocusItem) => {
    if (item.isAutoGenerated) return; // auto items are read-only in DB
    await updateMutation.mutateAsync({ id: item.id, data: { done: !item.done } });
    void refetch();
  };

  const goToShipment = (shipmentId: number) => {
    setLocation(`/inbox?shipment=${shipmentId}`);
    onClose();
  };

  const progressPct = totalCount > 0 ? Math.round((doneCount / totalCount) * 100) : 0;

  return (
    <>
      {/* Scrim */}
      <div
        className={`fixed inset-0 z-40 bg-black/20 transition-opacity duration-200 ${open ? "opacity-100" : "opacity-0 pointer-events-none"}`}
        onClick={onClose}
      />

      {/* Drawer */}
      <div
        className={`fixed top-0 right-0 h-full z-50 w-[360px] bg-white shadow-2xl flex flex-col transition-transform duration-250 ease-out ${open ? "translate-x-0" : "translate-x-full"}`}
        style={{ borderLeft: "1px solid #E5EAF0" }}
      >
        {/* Header */}
        <div className="flex items-center gap-2 px-4 py-3 border-b border-[#E5EAF0] shrink-0">
          <Zap className="w-4 h-4 text-[#9000FF]" fill="#9000FF" />
          <span className="font-bold text-sm text-[#212833] flex-1">Today's Focus</span>
          {pendingCount > 0 && (
            <span className="text-[10px] font-bold bg-[#9000FF] text-white rounded-full px-1.5 py-0.5 min-w-[18px] text-center">
              {pendingCount}
            </span>
          )}
          <button onClick={onClose} className="ml-1 p-1 rounded hover:bg-[#F7F9FA] text-[#9E9FAE] hover:text-[#212833] transition-colors">
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Progress bar */}
        {totalCount > 0 && (
          <div className="px-4 py-2.5 border-b border-[#F7F9FA] shrink-0">
            <div className="flex items-center justify-between mb-1.5">
              <span className="text-[11px] text-[#5E687B]">
                <span className="text-emerald-600 font-semibold">{doneCount} of {totalCount}</span> tasks done
              </span>
              <span className="text-[10px] text-[#9E9FAE]">{progressPct}%</span>
            </div>
            <div className="h-1.5 bg-[#F0F2F5] rounded-full overflow-hidden">
              <div
                className="h-full bg-emerald-500 rounded-full transition-all duration-500"
                style={{ width: `${progressPct}%` }}
              />
            </div>
          </div>
        )}

        {/* Task list */}
        <div className="flex-1 overflow-y-auto min-h-0">
          {/* Human tasks */}
          <div className="px-3 pt-3 pb-1 space-y-1">
            {items.length === 0 && (
              <p className="text-center text-[#9E9FAE] text-xs py-8">No tasks for today</p>
            )}
            {items.map(item => (
              <div
                key={item.id}
                className={`flex items-start gap-2.5 p-2.5 rounded-lg hover:bg-[#F7F9FA] group cursor-pointer transition-colors ${item.done ? "opacity-50" : ""}`}
                onClick={() => goToShipment(item.shipmentId)}
              >
                {/* Checkbox / done indicator */}
                <button
                  className={`mt-0.5 w-4 h-4 rounded-full border-2 flex items-center justify-center shrink-0 transition-colors ${
                    item.done
                      ? "border-[#9000FF] bg-[#9000FF]"
                      : "border-[#C0C8D4] hover:border-[#9000FF]"
                  } ${item.isAutoGenerated ? "opacity-40 cursor-not-allowed" : ""}`}
                  onClick={e => { e.stopPropagation(); void toggleItem(item); }}
                  disabled={item.isAutoGenerated}
                  title={item.isAutoGenerated ? "Auto-generated item" : item.done ? "Mark undone" : "Mark done"}
                >
                  {item.done && <Check className="w-2.5 h-2.5 text-white" strokeWidth={3} />}
                </button>

                <div className="flex-1 min-w-0">
                  <p className={`text-[12px] font-medium text-[#212833] leading-snug ${item.done ? "line-through text-[#9E9FAE]" : ""}`}>
                    {item.title}
                  </p>
                  <div className="flex items-center gap-1.5 mt-0.5">
                    <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${URGENCY_DOT[item.urgency] ?? "bg-[#C0C8D4]"}`} />
                    <span className="text-[10px] text-[#9E9FAE]">
                      {sourceIcon(item.source)} {item.source}
                    </span>
                    <span className="text-[10px] text-[#9E9FAE]">·</span>
                    <span className={`text-[10px] font-medium ${
                      item.sourceAge === "Today" ? "text-red-500" :
                      item.sourceAge === "Yesterday" ? "text-amber-500" :
                      "text-[#9E9FAE]"
                    }`}>{item.sourceAge}</span>
                  </div>
                </div>

                <ChevronRight className="w-3.5 h-3.5 text-[#C0C8D4] shrink-0 mt-0.5 opacity-0 group-hover:opacity-100 transition-opacity" />
              </div>
            ))}
          </div>

          {/* AI Suggestions divider */}
          <div className="px-3 py-2 mt-1">
            <div className="flex items-center gap-2">
              <div className="flex-1 h-px bg-[#E5EAF0]" />
              <div className="flex items-center gap-1.5 px-2 py-0.5">
                <Sparkles className="w-3 h-3 text-[#9000FF]" />
                <span className="text-[10px] font-bold text-[#5E687B] uppercase tracking-wider">AI Suggestions</span>
                <span className="text-[9px] font-bold bg-[#9000FF] text-white rounded-full px-1.5 py-0.5">AI</span>
              </div>
              <div className="flex-1 h-px bg-[#E5EAF0]" />
            </div>
            <p className="text-center text-[10px] text-[#9E9FAE] mt-1">Generated by FlowForgeIQ · Tap to act</p>
          </div>

          {/* AI suggestion cards */}
          <div className="px-3 pb-4 space-y-2">
            {suggestionsLoading && (
              <div className="flex items-center gap-2 justify-center py-6 text-[#9E9FAE]">
                <Loader2 className="w-4 h-4 animate-spin" />
                <span className="text-xs">Generating suggestions…</span>
              </div>
            )}
            {suggestionsError && (
              <div className="flex items-center gap-2 justify-center py-4 text-[#9E9FAE]">
                <AlertCircle className="w-4 h-4" />
                <span className="text-xs">Couldn't load suggestions</span>
              </div>
            )}
            {!suggestionsLoading && !suggestionsError && suggestions.map((s, i) => (
              <div
                key={i}
                className="rounded-lg border border-dashed border-[#9000FF]/30 bg-[#9000FF]/[0.03] p-3 cursor-pointer hover:bg-[#9000FF]/[0.06] hover:border-[#9000FF]/50 transition-colors group"
                onClick={() => goToShipment(s.shipmentId)}
              >
                <div className="flex items-start gap-2">
                  <Sparkles className="w-3.5 h-3.5 text-[#9000FF] shrink-0 mt-0.5" />
                  <div className="flex-1 min-w-0">
                    <p className="text-[12px] font-medium text-[#212833] leading-snug">{s.title}</p>
                    <p className="text-[11px] text-[#5E687B] mt-0.5 leading-snug">{s.detail}</p>
                    <div className="flex items-center gap-1 mt-1.5">
                      <span className="text-[11px] font-semibold text-[#9000FF] group-hover:text-[#7A00D9] transition-colors">
                        {s.action}
                      </span>
                      <ArrowRight className="w-3 h-3 text-[#9000FF]" />
                    </div>
                  </div>
                </div>
              </div>
            ))}
            {!suggestionsLoading && !suggestionsError && suggestions.length === 0 && suggestionsLoaded && (
              <p className="text-center text-[11px] text-[#9E9FAE] py-4">No suggestions right now — all shipments look on track.</p>
            )}
          </div>
        </div>
      </div>
    </>
  );
}

export function TodaysFocusButton({ onClick }: { onClick: () => void }) {
  const { data } = useListFocusItems();
  const count = data?.pendingCount ?? 0;

  return (
    <button
      onClick={onClick}
      className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-[#9000FF] text-white text-xs font-bold hover:bg-[#7A00D9] transition-colors shrink-0"
    >
      <Zap className="w-3.5 h-3.5" fill="white" />
      <span>Today's Focus</span>
      {count > 0 && (
        <span className="bg-white text-[#9000FF] text-[9px] font-extrabold rounded-full px-1.5 py-0.5 min-w-[16px] text-center leading-none">
          {count}
        </span>
      )}
    </button>
  );
}
