import React, { useState, useEffect, useRef } from "react";
import { Zap, X, Check, Sparkles, ArrowRight, Loader2, ChevronRight, AlertCircle, Clock, User } from "lucide-react";
import { useListFocusItems, useUpdateFocusItem } from "@workspace/api-client-react";
import type { FocusItem, AiSuggestion } from "@workspace/api-client-react";
import { useLocation } from "wouter";
import { useCopilot } from "@/lib/CopilotContext";

export type AIDrawerTab = "focus" | "ask";

interface AIDrawerProps {
  open: boolean;
  onClose: () => void;
  initialTab?: AIDrawerTab;
}

const URGENCY_DOT: Record<string, string> = {
  high: "bg-red-500",
  medium: "bg-amber-400",
  low: "bg-emerald-400",
};

const SOURCE_ICON: Record<string, string> = {
  WhatsApp: "💬",
  Email: "✉️",
  Gmail: "✉️",
  Tracker: "🗂️",
  Sheets: "📊",
  "Risk Radar": "⚠️",
  default: "📌",
};

function sourceIcon(source: string) {
  return SOURCE_ICON[source] ?? SOURCE_ICON.default;
}

type ConversationTurn = { role: "user" | "assistant"; content: string };
const ACTION_CHIPS = ["Draft reply", "Flag payment", "Show all tasks"];

export function AIDrawer({ open, onClose, initialTab = "focus" }: AIDrawerProps) {
  const [tab, setTab] = useState<AIDrawerTab>(initialTab);
  const [, setLocation] = useLocation();

  // Focus tab state
  const { data, refetch } = useListFocusItems();
  const updateMutation = useUpdateFocusItem();
  const [suggestions, setSuggestions] = useState<AiSuggestion[]>([]);
  const [suggestionsLoaded, setSuggestionsLoaded] = useState(false);
  const [suggestionsLoading, setSuggestionsLoading] = useState(false);
  const [suggestionsError, setSuggestionsError] = useState(false);
  const fetchedRef = useRef(false);
  const basePath = import.meta.env.BASE_URL.replace(/\/$/, "");

  // Ask AI tab state
  const { contextHint, suggestions: copilotSuggestions, inputRef, history, addToHistory } = useCopilot();
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(false);
  const [aiError, setAiError] = useState("");
  const [conversationHistory, setConversationHistory] = useState<ConversationTurn[]>([]);
  const [pendingMessage, setPendingMessage] = useState("");
  const [historyIndex, setHistoryIndex] = useState(-1);
  const draftRef = useRef("");
  const scrollRef = useRef<HTMLDivElement>(null);
  const askInputRef = useRef<HTMLInputElement>(null);

  // Sync initial tab when prop changes
  useEffect(() => { setTab(initialTab); }, [initialTab]);

  // Focus on ask input when switching to ask tab
  useEffect(() => {
    if (open && tab === "ask") {
      setTimeout(() => askInputRef.current?.focus(), 100);
    }
  }, [open, tab]);

  // Scroll AI conversation to bottom
  useEffect(() => {
    if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
  }, [conversationHistory, pendingMessage, loading]);

  // Load AI suggestions once when drawer first opens
  useEffect(() => {
    if (!open || fetchedRef.current) return;
    fetchedRef.current = true;
    setSuggestionsLoading(true);
    setSuggestionsError(false);
    void fetch(`${basePath}/api/focus/suggestions`, { method: "POST" })
      .then(r => r.json())
      .then((d: { suggestions: AiSuggestion[] }) => {
        setSuggestions(d.suggestions ?? []);
        setSuggestionsLoaded(true);
      })
      .catch(() => { setSuggestionsError(true); })
      .finally(() => { setSuggestionsLoading(false); });
  }, [open, basePath]);

  const items: FocusItem[] = data?.items ?? [];
  const pendingCount = data?.pendingCount ?? 0;
  const doneCount = items.filter(i => i.done).length;
  const totalCount = items.length;
  const progressPct = totalCount > 0 ? Math.round((doneCount / totalCount) * 100) : 0;

  const toggleItem = async (item: FocusItem) => {
    if (item.isAutoGenerated) return;
    await updateMutation.mutateAsync({ id: item.id, data: { done: !item.done } });
    void refetch();
  };

  const goToShipment = (shipmentId: number) => {
    setLocation(`/?shipment=${shipmentId}`);
    onClose();
  };

  async function submitAskQuery(text: string) {
    if (!text || loading) return;
    setHistoryIndex(-1);
    draftRef.current = "";
    addToHistory(text);
    setLoading(true);
    setAiError("");
    setPendingMessage(text);
    setQuery("");
    try {
      const res = await fetch(`${basePath}/api/copilot/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: text,
          contextHint: contextHint !== "Ask FlowForgeIQ anything" ? contextHint : undefined,
          history: conversationHistory,
        }),
      });
      if (!res.ok) throw new Error("Request failed");
      const d = (await res.json()) as { reply: string };
      setConversationHistory(prev => [
        ...prev,
        { role: "user", content: text },
        { role: "assistant", content: d.reply },
      ]);
      setPendingMessage("");
    } catch {
      setAiError("Couldn't connect to AI. Please try again.");
      setPendingMessage("");
    } finally {
      setLoading(false);
    }
  }

  function clearConversation() {
    setConversationHistory([]);
    setPendingMessage("");
    setQuery("");
    setAiError("");
    setLoading(false);
    setHistoryIndex(-1);
    draftRef.current = "";
  }

  function handleAskKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") { void submitAskQuery(query.trim()); return; }
    if (e.key === "ArrowUp") {
      e.preventDefault();
      if (!history.length) return;
      const next = historyIndex + 1;
      if (next >= history.length) return;
      if (historyIndex === -1) draftRef.current = query;
      setHistoryIndex(next);
      setQuery(history[next]);
      return;
    }
    if (e.key === "ArrowDown") {
      e.preventDefault();
      if (historyIndex <= -1) return;
      const next = historyIndex - 1;
      setHistoryIndex(next);
      setQuery(next === -1 ? draftRef.current : history[next]);
    }
  }

  const hasConversation = conversationHistory.length > 0;

  return (
    <>
      {/* Scrim */}
      <div
        className={`fixed inset-0 z-40 bg-black/20 transition-opacity duration-200 ${open ? "opacity-100" : "opacity-0 pointer-events-none"}`}
        onClick={onClose}
      />

      {/* Drawer */}
      <div
        className={`fixed top-0 right-0 h-full z-50 w-[380px] bg-white shadow-2xl flex flex-col transition-transform duration-250 ease-out ${open ? "translate-x-0" : "translate-x-full"}`}
        style={{ borderLeft: "1px solid #E5EAF0" }}
      >
        {/* Header */}
        <div className="flex items-center gap-2 px-4 py-3 border-b border-[#E5EAF0] shrink-0">
          <Sparkles className="w-4 h-4 text-[#9000FF]" />
          <span className="font-bold text-sm text-[#212833] flex-1">FlowForgeIQ AI</span>
          <button onClick={onClose} className="p-1 rounded hover:bg-[#F7F9FA] text-[#9E9FAE] hover:text-[#212833] transition-colors">
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-[#E5EAF0] shrink-0 px-4">
          <button
            onClick={() => setTab("focus")}
            className={`flex items-center gap-1.5 py-2.5 pr-4 text-xs font-semibold border-b-2 transition-colors ${
              tab === "focus"
                ? "border-[#9000FF] text-[#9000FF]"
                : "border-transparent text-[#5E687B] hover:text-[#212833]"
            }`}
          >
            <Zap className="w-3.5 h-3.5" fill={tab === "focus" ? "#9000FF" : "none"} />
            Today's Focus
            {pendingCount > 0 && (
              <span className={`text-[9px] font-extrabold rounded-full px-1.5 py-0.5 min-w-[16px] text-center leading-none ${tab === "focus" ? "bg-[#9000FF] text-white" : "bg-[#F0F4F8] text-[#5E687B]"}`}>
                {pendingCount}
              </span>
            )}
          </button>
          <button
            onClick={() => setTab("ask")}
            className={`flex items-center gap-1.5 py-2.5 px-4 text-xs font-semibold border-b-2 transition-colors ${
              tab === "ask"
                ? "border-[#9000FF] text-[#9000FF]"
                : "border-transparent text-[#5E687B] hover:text-[#212833]"
            }`}
          >
            <Sparkles className="w-3.5 h-3.5" />
            Ask AI
          </button>
        </div>

        {/* ── FOCUS TAB ── */}
        {tab === "focus" && (
          <div className="flex-1 overflow-y-auto min-h-0 flex flex-col">
            {/* Progress bar */}
            {totalCount > 0 && (
              <div className="px-4 py-2.5 border-b border-[#F7F9FA] shrink-0">
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-[11px] text-[#5E687B]">
                    <span className="text-emerald-600 font-semibold">{doneCount} of {totalCount}</span> tasks done
                  </span>
                  <span className="text-[10px] text-[#9E9FAE]">{progressPct}%</span>
                </div>
                <div className="h-1.5 bg-[#F0F2F5] rounded-full overflow-hidden">
                  <div className="h-full bg-emerald-500 rounded-full transition-all duration-500" style={{ width: `${progressPct}%` }} />
                </div>
              </div>
            )}

            {/* Task items */}
            <div className="px-3 pt-3 pb-1 space-y-1">
              {items.length === 0 && (
                <p className="text-center text-[#9E9FAE] text-xs py-8">No tasks for today</p>
              )}
              {items.map(item => (
                <div
                  key={item.id}
                  className={`flex items-start gap-2.5 p-2.5 rounded-lg hover:bg-[#F7F9FA] group cursor-pointer transition-colors ${item.done ? "opacity-50" : ""}`}
                  onClick={() => goToShipment(item.shipmentId)}
                >
                  <button
                    className={`mt-0.5 w-4 h-4 rounded-full border-2 flex items-center justify-center shrink-0 transition-colors ${
                      item.done ? "border-[#9000FF] bg-[#9000FF]" : "border-[#C0C8D4] hover:border-[#9000FF]"
                    } ${item.isAutoGenerated ? "opacity-40 cursor-not-allowed" : ""}`}
                    onClick={e => { e.stopPropagation(); void toggleItem(item); }}
                    disabled={item.isAutoGenerated}
                    title={item.isAutoGenerated ? "Auto-generated item" : item.done ? "Mark undone" : "Mark done"}
                  >
                    {item.done && <Check className="w-2.5 h-2.5 text-white" strokeWidth={3} />}
                  </button>
                  <div className="flex-1 min-w-0">
                    <p className={`text-[12px] font-medium text-[#212833] leading-snug ${item.done ? "line-through text-[#9E9FAE]" : ""}`}>
                      {item.title}
                    </p>
                    <div className="flex items-center gap-1.5 mt-0.5">
                      <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${URGENCY_DOT[item.urgency] ?? "bg-[#C0C8D4]"}`} />
                      <span className="text-[10px] text-[#9E9FAE]">{sourceIcon(item.source)} {item.source}</span>
                      <span className="text-[10px] text-[#9E9FAE]">·</span>
                      <span className={`text-[10px] font-medium ${
                        item.sourceAge === "Today" ? "text-red-500" :
                        item.sourceAge === "Yesterday" ? "text-amber-500" : "text-[#9E9FAE]"
                      }`}>{item.sourceAge}</span>
                    </div>
                  </div>
                  <ChevronRight className="w-3.5 h-3.5 text-[#C0C8D4] shrink-0 mt-0.5 opacity-0 group-hover:opacity-100 transition-opacity" />
                </div>
              ))}
            </div>

            {/* AI Suggestions divider */}
            <div className="px-3 py-2 mt-1">
              <div className="flex items-center gap-2">
                <div className="flex-1 h-px bg-[#E5EAF0]" />
                <div className="flex items-center gap-1.5 px-2 py-0.5">
                  <Sparkles className="w-3 h-3 text-[#9000FF]" />
                  <span className="text-[10px] font-bold text-[#5E687B] uppercase tracking-wider">AI Suggestions</span>
                  <span className="text-[9px] font-bold bg-[#9000FF] text-white rounded-full px-1.5 py-0.5">AI</span>
                </div>
                <div className="flex-1 h-px bg-[#E5EAF0]" />
              </div>
              <p className="text-center text-[10px] text-[#9E9FAE] mt-1">Generated from email & date analysis · Tap to act</p>
            </div>

            {/* AI suggestion cards */}
            <div className="px-3 pb-4 space-y-2">
              {suggestionsLoading && (
                <div className="flex items-center gap-2 justify-center py-6 text-[#9E9FAE]">
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span className="text-xs">Analysing shipments…</span>
                </div>
              )}
              {suggestionsError && (
                <div className="flex items-center gap-2 justify-center py-4 text-[#9E9FAE]">
                  <AlertCircle className="w-4 h-4" />
                  <span className="text-xs">Couldn't load suggestions</span>
                </div>
              )}
              {!suggestionsLoading && !suggestionsError && suggestions.map((s, i) => (
                <div
                  key={i}
                  className="rounded-lg border border-dashed border-[#9000FF]/30 bg-[#9000FF]/[0.03] p-3 cursor-pointer hover:bg-[#9000FF]/[0.06] hover:border-[#9000FF]/50 transition-colors group"
                  onClick={() => goToShipment(s.shipmentId)}
                >
                  <div className="flex items-start gap-2">
                    <Sparkles className="w-3.5 h-3.5 text-[#9000FF] shrink-0 mt-0.5" />
                    <div className="flex-1 min-w-0">
                      <p className="text-[12px] font-medium text-[#212833] leading-snug">{s.title}</p>
                      <p className="text-[11px] text-[#5E687B] mt-0.5 leading-snug">{s.detail}</p>
                      <div className="flex items-center gap-1 mt-1.5">
                        <span className="text-[11px] font-semibold text-[#9000FF] group-hover:text-[#7A00D9] transition-colors">{s.action}</span>
                        <ArrowRight className="w-3 h-3 text-[#9000FF]" />
                      </div>
                    </div>
                  </div>
                </div>
              ))}
              {!suggestionsLoading && !suggestionsError && suggestions.length === 0 && suggestionsLoaded && (
                <p className="text-center text-[11px] text-[#9E9FAE] py-4">No suggestions right now — all shipments look on track.</p>
              )}
            </div>
          </div>
        )}

        {/* ── ASK AI TAB ── */}
        {tab === "ask" && (
          <div className="flex-1 flex flex-col min-h-0">
            {/* Conversation */}
            <div ref={scrollRef} className="flex-1 overflow-y-auto px-4 pt-4 pb-2 space-y-3 min-h-0">
              {!hasConversation && !pendingMessage && (
                <div className="flex flex-col items-center justify-center h-full gap-3 pb-8">
                  <div className="w-10 h-10 rounded-full bg-[#9000FF]/10 flex items-center justify-center">
                    <Sparkles className="w-5 h-5 text-[#9000FF]" />
                  </div>
                  <p className="text-[13px] font-medium text-[#212833] text-center">Ask FlowForgeIQ anything</p>
                  <p className="text-[11px] text-[#9E9FAE] text-center max-w-[240px] leading-relaxed">
                    Ask about shipments, drafts, supplier updates, payment status, or anything on your mind.
                  </p>
                  {copilotSuggestions.length > 0 && (
                    <div className="w-full space-y-1.5 mt-2">
                      {copilotSuggestions.map((s, i) => (
                        <button
                          key={i}
                          onClick={() => void submitAskQuery(s)}
                          className="w-full flex items-center gap-2 px-3 py-2 rounded-lg bg-[#F7F9FA] hover:bg-[#F0F4F8] text-left transition-colors group"
                        >
                          <Sparkles size={11} className="text-[#9000FF]/50 shrink-0 group-hover:text-[#9000FF] transition-colors" />
                          <span className="text-xs text-[#212833] truncate">{s}</span>
                        </button>
                      ))}
                    </div>
                  )}
                  {history.length > 0 && (
                    <div className="w-full mt-1">
                      <p className="text-[10px] font-semibold text-[#9E9FAE] uppercase tracking-wide mb-1.5">Recent</p>
                      {history.slice(0, 4).map((item, i) => (
                        <button
                          key={i}
                          onClick={() => void submitAskQuery(item)}
                          className="w-full flex items-center gap-2 px-3 py-1.5 rounded-lg hover:bg-[#F0F4F8] text-left transition-colors"
                        >
                          <Clock size={11} className="text-[#9E9FAE] shrink-0" />
                          <span className="text-xs text-[#212833] truncate">{item}</span>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {conversationHistory.map((turn, i) =>
                turn.role === "user" ? (
                  <div key={i} className="flex items-start gap-2 justify-end">
                    <p className="text-xs text-[#212833] bg-[#F0F4F8] rounded-xl rounded-tr-sm px-3 py-2 max-w-[85%] leading-relaxed">{turn.content}</p>
                    <span className="shrink-0 mt-0.5 w-5 h-5 rounded-full bg-[#9000FF]/10 flex items-center justify-center">
                      <User size={10} className="text-[#9000FF]" />
                    </span>
                  </div>
                ) : (
                  <div key={i} className="flex items-start gap-2">
                    <Sparkles size={13} className="text-[#9000FF] shrink-0 mt-0.5" />
                    <p className="text-xs text-[#212833] leading-relaxed max-w-[90%]">{turn.content}</p>
                  </div>
                )
              )}

              {pendingMessage && (
                <div className="flex items-start gap-2 justify-end">
                  <p className="text-xs text-[#212833] bg-[#F0F4F8] rounded-xl rounded-tr-sm px-3 py-2 max-w-[85%] leading-relaxed">{pendingMessage}</p>
                  <span className="shrink-0 mt-0.5 w-5 h-5 rounded-full bg-[#9000FF]/10 flex items-center justify-center">
                    <User size={10} className="text-[#9000FF]" />
                  </span>
                </div>
              )}

              {loading && (
                <div className="flex items-start gap-2">
                  <Sparkles size={13} className="text-[#9000FF] shrink-0 mt-0.5" />
                  <span className="flex items-center gap-1.5 mt-0.5">
                    <span className="w-1.5 h-1.5 bg-[#9000FF]/40 rounded-full animate-bounce" style={{ animationDelay: "0ms" }} />
                    <span className="w-1.5 h-1.5 bg-[#9000FF]/40 rounded-full animate-bounce" style={{ animationDelay: "150ms" }} />
                    <span className="w-1.5 h-1.5 bg-[#9000FF]/40 rounded-full animate-bounce" style={{ animationDelay: "300ms" }} />
                  </span>
                </div>
              )}

              {aiError && (
                <div className="flex items-start gap-2">
                  <AlertCircle size={13} className="text-red-500 shrink-0 mt-0.5" />
                  <p className="text-xs text-red-600 leading-relaxed">{aiError}</p>
                </div>
              )}
            </div>

            {/* Action chips */}
            {!loading && !aiError && hasConversation && (
              <div className="px-4 py-2 border-t border-[#F0F4F8] flex flex-wrap items-center gap-2 shrink-0">
                {ACTION_CHIPS.map(chip => (
                  <button
                    key={chip}
                    onClick={() => { setQuery(chip); askInputRef.current?.focus(); }}
                    className="text-[10px] bg-[#9000FF]/[0.08] text-[#9000FF] border border-[#9000FF]/20 px-2.5 py-1 rounded-full hover:bg-[#9000FF]/[0.15] font-semibold transition-colors"
                  >
                    {chip}
                  </button>
                ))}
                {conversationHistory.length >= 4 && (
                  <button onClick={clearConversation} className="ml-auto text-[10px] text-[#9E9FAE] hover:text-[#5E687B] transition-colors font-medium">
                    New conversation
                  </button>
                )}
              </div>
            )}

            {/* Input */}
            <div className="px-4 py-3 border-t border-[#E5EAF0] shrink-0">
              <div className="flex items-center gap-2 bg-[#F0F4F8] rounded-full px-3 py-2 focus-within:bg-white focus-within:ring-1 focus-within:ring-[#9000FF]/20 focus-within:border focus-within:border-[#9000FF]/30 transition-all">
                <Sparkles className="w-3.5 h-3.5 text-[#9000FF]/50 shrink-0" />
                <input
                  ref={askInputRef}
                  type="text"
                  value={query}
                  onChange={e => { setQuery(e.target.value); setHistoryIndex(-1); draftRef.current = ""; }}
                  onKeyDown={handleAskKeyDown}
                  placeholder={hasConversation ? "Ask a follow-up…" : `${contextHint}`}
                  className="flex-1 bg-transparent text-xs text-[#212833] placeholder:text-[#9E9FAE] outline-none"
                />
                {query && (
                  <button
                    onClick={() => void submitAskQuery(query.trim())}
                    className="shrink-0 w-5 h-5 rounded-full bg-[#9000FF] flex items-center justify-center hover:bg-[#7A00D9] transition-colors"
                  >
                    <ArrowRight className="w-3 h-3 text-white" />
                  </button>
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    </>
  );
}

export function AISparklesButton({ onClick, pendingCount }: { onClick: () => void; pendingCount?: number }) {
  return (
    <button
      onClick={onClick}
      className="relative flex items-center justify-center w-8 h-8 rounded-lg hover:bg-[#F0F4F8] transition-colors group"
      title="FlowForgeIQ AI"
    >
      <Sparkles className="w-4 h-4 text-[#9000FF] group-hover:text-[#7A00D9] transition-colors" />
      {pendingCount != null && pendingCount > 0 && (
        <span className="absolute -top-0.5 -right-0.5 min-w-[14px] h-[14px] bg-[#9000FF] text-white text-[8px] font-extrabold rounded-full flex items-center justify-center px-0.5 leading-none">
          {pendingCount > 9 ? "9+" : pendingCount}
        </span>
      )}
    </button>
  );
}
